# Generated by Django 3.1 on 2022-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220827_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='subphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
